name: Push on branch
run-name: Pushed commit(s) on branch ${{ github.ref_name }} by @${{ github.actor }}.
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: Test the code
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: {{ matrix.os }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.3
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
      - name: Test the code
        run: ./mvnw test